### ISSUE TITLE
Crashes on trying to play a particular song

### ISSUE THREAD

**Issue by RiflerRick** [ProjectRecommend/Recommend#9]
### Expected behavior

Should have played the song

### Actual behavior

Got this error `D:/songs/Kabhi_Shaam_Dhale-Mahalakshmi_Iyer-www.Mp3Mad.Com.mp3
get recommendation, nothing is in Cache for this song
Traceback (most recent call last):
  File "main.py", line 366, in currentMediaChangedHandler
    recommendModel = self.manageCache.queryCache(self.currentPlayingMediaUrl, self.manageLocalStorage)
  File "C:\Users\riflerRick\Desktop\NiitUniversityCSE_course\3rdyr\semester5\softwareEngineering\project\gitRepos\Recommend\recommend\classifier\ManageCacheModule.py", line 175, in queryCache
    relevantSongDict = getRecom.fetchRelevantSongOffline(SPath)
  File "C:\Users\riflerRick\Desktop\NiitUniversityCSE_course\3rdyr\semester5\softwareEngineering\project\gitRepos\Recommend\recommend\classifier\GetRecommendationModule.py", line 110, in fetchRelevantSongOffline
    relevantSongDict[path] = self.metadataToPara(path)
  File "C:\Users\riflerRick\Desktop\NiitUniversityCSE_course\3rdyr\semester5\softwareEngineering\project\gitRepos\Recommend\recommend\classifier\GetRecommendationModule.py", line 184, in metadataToPara
    text = text + metadataDict.get(item) + " "
TypeError: Can't convert 'NoneType' object to str implicitly`

### Steps to reproduce behavior

I tried playing a song and this is the error I got. The error is very specific, it will only happen under certain circumstances only.

**Comment by RiflerRick** [comment]
also got same error for:

`D:/songs/artist+-+WHITHNEY+Houston-I+will+always+love+you(music.naij.com).mp3
get recommendation, nothing is in Cache for this song
Traceback (most recent call last):
  File "main.py", line 366, in currentMediaChangedHandler
    recommendModel = self.manageCache.queryCache(self.currentPlayingMediaUrl, self.manageLocalStorage)
  File "C:\Users\riflerRick\Desktop\NiitUniversityCSE_course\3rdyr\semester5\softwareEngineering\project\gitRepos\Recommend\recommend\classifier\ManageCacheModule.py", line 175, in queryCache
    relevantSongDict = getRecom.fetchRelevantSongOffline(SPath)
  File "C:\Users\riflerRick\Desktop\NiitUniversityCSE_course\3rdyr\semester5\softwareEngineering\project\gitRepos\Recommend\recommend\classifier\GetRecommendationModule.py", line 110, in fetchRelevantSongOffline
    relevantSongDict[path] = self.metadataToPara(path)
  File "C:\Users\riflerRick\Desktop\NiitUniversityCSE_course\3rdyr\semester5\softwareEngineering\project\gitRepos\Recommend\recommend\classifier\GetRecommendationModule.py", line 184, in metadataToPara
    text = text + metadataDict.get(item) + " "
TypeError: Can't convert 'NoneType' object to str implicitly`

**Comment by RiflerRick** [comment]
I feel this error happens for those songs where there is no lyrics USLT tag is returning None

**Comment by electron0zero** [comment]
@RiflerRick can you reproduce this issue now ?
